#!/usr/bin/env bash
# load balancer script installer / config

# istall
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9
apt-get install haproxy=2.9.\*

# config HAProxy file using a roundrobin algorithm
echo '
frontend khalidev.tech
	bind *:80
	default_backend web_backend
backend  web_backend
	balance roundrobin
	server 531316-web-01 54.162.97.17:80 check
	server 531316-web-02 34.224.83.106:80 check
' >> /etc/haproxy/haproxy.cfg

# restart HAProxy
service haproxy restart
