#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

FILE_NAME=$(date "+%d-%m-%Y.tar.gz")
mysqldump -u root -p "$1" > backup.sql
tar -czvf "$FILE_NAME" backup.sql
