#!/usr/bin/env bash
# script to make Nginx listen on port 80

# Configure Nginx to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx service
sudo service nginx restart
