#!/usr/bin/env bash
# This script is displaying The content of the current directory In a list format Where only the part of the name after the first dash is displayed

files=$(ls)

for file in $files
do
	name=$(echo "$file" | cut -d'-' -f2-)
	echo "$name"
done
